nama = input("Nama                      :")
nim = input("NIM                       :")
paralel = input("Kelas Paralel             :")
ttl = input("Tempat/Tanggal Lahir      :")
alamat = input("Alamat                    :")
hobby = input ("Hobby                     :")
nohp  = input ("No.Hp                     :")

print("\nNama                      :"+nama)
print("NIM                       :"+nim)
print("Kelas Paralel             :"+paralel)
print("Tempat/Tanggal Lahir      :"+ttl)
print("Alamat                    :"+alamat)
print("Hobby                     :"+hobby)
print("No.Hp                     :"+nohp)
